feat: module page initiate
gdsc-nits-org/tecnoesis-web pull request #18
Opened 2024-01-09 16:25 UTC by Rupantar-Borphukan

2024-01-10 12:31 UTC, codadept requested changes

2024-01-10 12:31 UTC, codadept commented on src/pages/Module/Module.jsx
> +import Module from "../../components/Module/Game";
The default export name is Game and you are importing as Module?

2024-01-10 12:31 UTC, codadept commented on src/pages/Module/Module.jsx
> +          <Footer/>
Footer should be common for all the pages so it should be present in App.jsx

2024-01-10 12:31 UTC, codadept commented on src/components/Module/Game.jsx
> +import React from 'react'
No need to import React

2024-01-10 12:34 UTC, codadept requested changes

2024-01-10 12:34 UTC, codadept commented on src/pages/Module/Module.jsx
> +import Footer from "../../components/Footer/Footer";
Chnage it to

```jsx
import { Footer } from "../../components";
```

2024-01-10 15:34 UTC, Rupantar-Borphukan commented on src/pages/Module/Module.jsx
> +          <Footer/>
ok bhaiya

2024-01-10 15:34 UTC, Rupantar-Borphukan commented on src/components/Module/Game.jsx
> +import React from 'react'
ok

2024-01-10 16:05 UTC, Rupantar-Borphukan commented on src/pages/Module/Module.jsx
> +import Module from "../../components/Module/Game";
ok I will fix it

2024-01-20 17:32 UTC, codadept commented
Closed due to inactivity

2024-01-20 17:32 UTC, closed without merging